
server:
  port: 9999
  contextPath: /uaa

security:
  user:
    name: root
    password: pass

security.oauth2.client:
  clientId: acme
  clientSecret: acmesecret
  authorized-grant-types: password,refresh_token #authorization_code,refresh_token,password
  scope: openid

logging.level.org.springframework.security: DEBUG
